### PR TITLE
Add screenshots to the README

### PR DESCRIPTION
**Pull request by Zotyamester**

### CODE REVIEW

**Comment by humdingerb** [comment]
Please remove all object files from the PR.

**Comment by Zotyamester** [comment]
Oh silly me! Sorry about that. I've just removed those from the commit. It should be fine now.

**Comment by Zotyamester** [comment]
By the way if I add a .gitignore to the repo would you accept that PR too?

**Comment by humdingerb** [comment]
Thanks!
Not sure what HaikuArchives' policy is on .gitignore...
Probably not for whole objects folders. At least I haven't seen that with any project.

**Pull request merged**
